export const CART_ADD_ITEM='CART-ADD-ITEM';
export const CART_REMOVE_ITEM='CART-REMOVE-ITEM';
export const CART_SAVE_SHIPPING_ADDRESS='CART-SAVE-SHIPPING-ADDRESS';
export const CART_SAVE_PAYMENT_METHOD='CART-SAVE-PAYMENT-METHOD';
export const CART_CLEAR='CART-CLEAR';
export const CART_LIST_ITEMS='CART-LIST-ITEMS';

